- name: Importing Certificate Database - {{import_certificate_database_kdb}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.certificate_databases.import_db
    isamapi:
      kdb      : "{{ import_certificate_database_kdb}}"
      stash    : "{{ import_certificate_database_stash }}"
  when: import_certificate_database_kdb is defined and import_certificate_database_stash is defined
  notify:
  - Commit Changes
