# main task to rename dynurl files
# Example:
#   dynurl_files
#     - id: dynurl.conf
#       new_name: new_dynurl.conf
---
- name: Upload dynurl files
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.url_mapping.rename
    isamapi:
      id: "{{ item.id }}"
      new_name: "{{  item.new_name }}"
  with_items: "{{ dynurl_files }}"
  notify: Commit Changes
