
---
- name: Read Certificates
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.all_certificates.get_all_certificates
  register: ret_obj

- name: Format output
  set_fact:
    all_certificates: "{{ret_obj.data}}"
