# main task to download trace files
---
- name: Get trace files
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.reverse_proxy.trace.export_file
    isamapi:
      instance_id: "{{ export_trace_rp_id }}"
      component_id: "{{ export_trace_component }}"
      file_id: "{{ item.id }}"
      filename: "{{ export_trace_prefix |default('')}}{{ item.id }}"
  with_items: "{{ trace_files_to_export }}"

