# Commit all changes made to date before configuring federation into reverse proxy
- meta: flush_handlers

- name: "Configure Reverse Proxy for Federation {{ federation_name }}"
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.federation_configuration.config
    isamapi:
      instance_id:   "{{ config_reverseproxy_federation_instance_id }}"
      federation_id: "{{ config_reverseproxy_federation_federation_id }}"
      hostname:      "{{ config_reverseproxy_federation_hostname }}"
      port:          "{{ config_reverseproxy_federation_port }}"
      username:      "{{ config_reverseproxy_federation_username }}"
      password:      "{{ config_reverseproxy_federation_password }}"
      reuse_certs:   "{{ config_reverseproxy_federation_reuse_certs }}"
      reuse_acls:    "{{ config_reverseproxy_federation_reuse_acls }}"
  when: config_reverseproxy_federation_name is defined and config_reverseproxy_federation_instance_id is defined
  notify:
    - Commit Changes
    - Restart Reverse Proxy